apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.repoName | dump }}
  annotations:
    argocd/app-name: ${{ values.repoName }}
    backstage.io/kubernetes-id: ${{ values.repoName }}
spec:
  destination:
    namespace: ${{ values.namespace }}
    server: https://kubernetes.default.svc
  project: ${{ values.argocd-project }}
  source:
    path: manifests/base
    repoURL: https://${{ values.sourceControl }}/${{ values.orgName }}/${{ values.repoName }}
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
  syncOptions:
    - CreateNamespace=true
